<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\BookPrices\**" />
    <Compile Remove="Features\BookStocks\**" />
    <Compile Remove="Features\UserAccount\**" />
    <Compile Remove="Features\Users\**" />
    <EmbeddedResource Remove="Features\BookPrices\**" />
    <EmbeddedResource Remove="Features\BookStocks\**" />
    <EmbeddedResource Remove="Features\UserAccount\**" />
    <EmbeddedResource Remove="Features\Users\**" />
    <None Remove="Features\BookPrices\**" />
    <None Remove="Features\BookStocks\**" />
    <None Remove="Features\UserAccount\**" />
    <None Remove="Features\Users\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ABC.Learning.Resource.Domain\ABC.Learning.Resource.Domain.csproj" />
    <ProjectReference Include="..\ABC.Learning.Resource.Exceptions\ABC.Learning.Resource.Exceptions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Features\BookRequest\AddBookRequest\Models\AddBookRequestDTO.cs" />
  </ItemGroup>

</Project>
